--BD2 - 2o Bim -Atividade de SQL - Exercícios de DDL - Tabelas do Projeto Pedido - Parte 1

--Queries implementadas na linguagem SQL aplicadas no SGBDR Oracle, apoiadas no
--SqlDeveloper. Utilizar o MER Físico e BD Pedido disponibilizado para treinamento da disciplina
--de Banco de Dados.

--1) Implementar o script DDL para criar as tabelas do BD de pedidos: CLIENTE, PF, PJ,
--PRODUTO, VENDEDOR, FONE_CLIENTE, FONE_VENDEDOR e PRATELEIRA.
--Colocar as regras de integridade básica no script de criação. Substituir todos os tipos de
--dados INTEGER que estão no modelo por NUMBER.


-- Tabela CLIENTE
CREATE TABLE CLIENTE
(
CODIGO          NUMBER  ,
NOME            VARCHAR2(60) NOT NULL,
RUA             VARCHAR2(80) NOT NULL,
NR              NUMBER(4) NOT NULL,
BAIRRO          VARCHAR2(50) NOT NULL,
COMPLEMENTO     VARCHAR2(100) NULL,
CIDADE          VARCHAR2(50) NOT NULL,
UF              VARCHAR2(2) NOT NULL,
CEP             VARCHAR2(10) NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO)
);

-- Tabela PF
CREATE TABLE PF
(
CODIGO_CLI      NUMBER  ,
CNPF            varchar2(14) NOT NULL,
RG              varchar2(10) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
CONSTRAINT PK_CLIENTE_PF PRIMARY KEY (CODIGO_CLI),
CONSTRAINT FK_PF_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE(CODIGO)
);


-- Tabela PJ
CREATE TABLE PJ
(
CODIGO_CLI  NUMBER  ,
CNPJ        varchar2(19) NOT NULL,
IE          varchar2(10) NOT NULL,
NOME_FANTASIA varchar2(19) NOT NULL,
CONSTRAINT PK_CLIENTE_PJ PRIMARY KEY (CODIGO_CLI),
CONSTRAINT FK_PJ_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE(CODIGO)
);


-- Tabela PRODUTO
CREATE TABLE PRODUTO 
(
CODIGO      NUMBER  ,
DESCRICAO   varchar2(80) NOT NULL,
UNID_MEDIDA varchar2(10) NOT NULL,
CONSTRAINT PK_PRODUTO PRIMARY KEY (CODIGO)
);


-- Tabela VENDEDOR
CREATE TABLE VENDEDOR 
(
MATRICULA   NUMBER  ,
NOME        varchar2(60) NOT NULL,
CNPF        varchar2(14) NOT NULL,
CONSTRAINT PK_VENDEDOR PRIMARY KEY(MATRICULA)
);


-- Tabela FONE_CLIENTE
CREATE TABLE   FONE_CLIENTE
(
NUMERO      varchar2(14) NOT NULL,
CODIGO_CLI  NUMBER  ,
CONSTRAINT PK_FONE_CLIENTE PRIMARY KEY (NUMERO, CODIGO_CLI),
CONSTRAINT FK_FONE_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE(CODIGO)
);


-- Tabela FONE_VENDEDOR
CREATE TABLE FONE_VENDEDOR 
(
NUMERO      varchar2(14) NOT NULL,
MATRICULA_VEN NUMBER    ,
CONSTRAINT PK_FONE_VENDEDOR PRIMARY KEY (NUMERO, MATRICULA_VEN),
CONSTRAINT FK_FONE_VENDEDOR FOREIGN KEY (MATRICULA_VEN) REFERENCES VENDEDOR(MATRICULA)
);


-- Tabela PRATELEIRA
CREATE TABLE PRATELEIRA 
(
CODIGO      NUMBER(3) NOT NULL,
DESCRICAO   varchar2(50) NOT NULL,
NUMERO_SECOES NUMBER(2) NOT NULL,
CONSTRAINT PK_PRATELEIRA PRIMARY KEY (CODIGO)
);